/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tests;

public class App {

    private int[] Array;

    public App(int[] array) {
        this.Array = array;
    }

    public int[] getArray() {
        return Array;
    }
}
